language: "python"
python:
  - 3.6.7
before_install:
  - echo $(pwd)
install:
  - sudo pip3 install -r requirements.txt
script:
  - python3 autosite.py --auto
addons:
  apt:
    packages:
      - python3
      - python3-pip
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./out
