language: "python"
python:
  - 3.6.7
before_install:
  - echo $(pwd)
install:
  - sudo pip install -r requirements.txt
script:
  - autosite --auto
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./out
